// AUTO-GENERATED from extension countries/*.json — country → reference city names.
// Regenerate by re-running the generator if the country lists change.
export const COUNTRY_CITIES: Record<string, string[]> = {
  "Austria": [
    "Bécs",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt am Wörthersee",
    "Villach",
    "Wels",
    "Sankt Pölten",
    "Dornbirn",
    "Wiener Neustadt",
    "Steyr",
    "Feldkirch",
    "Bregenz",
    "Leonding",
    "Klosterneuburg",
    "Baden bei Wien",
    "Wolfsberg",
    "Leoben",
    "Krems an der Donau",
    "Traun",
    "Amstetten",
    "Lustenau",
    "Kapfenberg",
    "Hallein",
    "Mödling",
    "Kufstein",
    "Traiskirchen",
    "Schwechat",
    "Stockerau",
    "Tulln an der Donau",
    "Saalfelden am Steinernen Meer",
    "Spittal an der Drau",
    "Telfs",
    "Ansfelden",
    "Perchtoldsdorf",
    "Hohenems",
    "Eisenstadt",
    "Bludenz",
    "Zell am See",
    "Hallstatt",
    "Kitzbühel",
    "Bad Ischl",
    "Melk",
    "Dürnstein",
    "Schladming",
    "Sölden",
    "Mayrhofen",
    "St. Anton am Arlberg",
    "Rust"
  ],
  "Belgium": [
    "Brüsszel",
    "Antwerpen",
    "Gent",
    "Charleroi",
    "Liège",
    "Brugge",
    "Namur",
    "Leuven",
    "Mons",
    "Mechelen",
    "Aalst",
    "La Louvière",
    "Kortrijk",
    "Hasselt",
    "Sint-Niklaas",
    "Oostende",
    "Tournai",
    "Genk",
    "Seraing",
    "Roeselare",
    "Mouscron",
    "Verviers",
    "Beringen",
    "Dendermonde",
    "Vilvoorde",
    "Lokeren",
    "Beveren",
    "Knokke-Heist",
    "Ieper",
    "Deinze",
    "Waregem",
    "Turnhout",
    "Geel",
    "Halle",
    "Ninove",
    "Sint-Truiden",
    "Tongeren",
    "Lier",
    "Mol",
    "Herentals",
    "Dinant",
    "Spa",
    "Durbuy",
    "Waterloo",
    "Bastogne",
    "Bouillon",
    "Rochefort",
    "Nieuwpoort",
    "Blankenberge",
    "De Haan"
  ],
  "Canada": [
    "Toronto",
    "Montréal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Québec City",
    "Winnipeg",
    "Mississauga",
    "Halifax",
    "Hamilton",
    "Victoria",
    "Niagara Falls",
    "Saskatoon",
    "Regina",
    "London",
    "Kitchener",
    "Windsor",
    "Kelowna",
    "St. John’s",
    "Richmond",
    "Vaughan",
    "Markham",
    "Brampton",
    "Surrey",
    "Burnaby",
    "Laval",
    "Longueuil",
    "Gatineau",
    "Sherbrooke",
    "Trois-Rivières",
    "Kingston",
    "Guelph",
    "Waterloo",
    "Burlington",
    "Oakville",
    "Oshawa",
    "Barrie",
    "Greater Sudbury",
    "Thunder Bay",
    "Moncton",
    "Fredericton",
    "Saint John",
    "Charlottetown",
    "Whitehorse",
    "Yellowknife",
    "Banff",
    "Canmore",
    "Whistler",
    "Nanaimo"
  ],
  "France": [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Saint-Étienne",
    "Toulon",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Clermont-Ferrand",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Perpignan",
    "Metz",
    "Besançon",
    "Orléans",
    "Rouen",
    "Mulhouse",
    "Caen",
    "Nancy",
    "Avignon",
    "Cannes",
    "La Rochelle",
    "Versailles",
    "Saint-Malo",
    "Colmar",
    "Biarritz",
    "Bayonne",
    "Antibes",
    "Ajaccio",
    "Chambéry",
    "Troyes",
    "Lourdes",
    "Carcassonne"
  ],
  "Greece": [
    "Athén",
    "Szaloniki",
    "Pátra",
    "Iráklio / Heraklion",
    "Lárisza",
    "Vólosz",
    "Ioánnina",
    "Haniá / Chania",
    "Rodosz",
    "Korfu / Kerkyra",
    "Réthimno",
    "Kavála",
    "Kalamáta",
    "Náfplio",
    "Tríkala",
    "Szérresz",
    "Alexandrúpoli",
    "Kateríni",
    "Mykonos",
    "Fíra / Santorini",
    "Ágios Nikólaos",
    "Szitía",
    "Chersónisos / Hersonissos",
    "Mália",
    "Kos",
    "Ermúpoli / Syros",
    "Zakynthos",
    "Argosztóli / Kefalonia",
    "Olympia",
    "Delphi"
  ],
  "Hong Kong": [
    "Central",
    "Tsim Sha Tsui",
    "Mong Kok",
    "Causeway Bay",
    "Wan Chai",
    "Yau Ma Tei",
    "Jordan",
    "Sham Shui Po",
    "Kowloon City",
    "Kwun Tong",
    "Tsuen Wan",
    "Sha Tin",
    "Tai Po",
    "Yuen Long",
    "Tuen Mun",
    "North Point",
    "Quarry Bay",
    "Aberdeen",
    "Stanley",
    "Lantau Island / Tung Chung"
  ],
  "Hungary": [
    "Budapest",
    "Kecskemét",
    "Pécs",
    "Békéscsaba",
    "Miskolc",
    "Szeged",
    "Székesfehérvár",
    "Győr",
    "Debrecen",
    "Eger",
    "Szolnok",
    "Tatabánya",
    "Salgótarján",
    "Kaposvár",
    "Nyíregyháza",
    "Szekszárd",
    "Szombathely",
    "Veszprém",
    "Zalaegerszeg",
    "Érd",
    "Sopron",
    "Nagykanizsa",
    "Dunaújváros",
    "Hódmezővásárhely",
    "Dunakeszi",
    "Szigetszentmiklós",
    "Cegléd",
    "Baja",
    "Mosónmagyaróvár",
    "Vác",
    "Gödöllő",
    "Esztergom",
    "Gyöngyös",
    "Kazinbarcika",
    "Orosháza",
    "Ajka",
    "Pápa",
    "Kiskunfélegyháza",
    "Hajdúböszörmény",
    "Gyula",
    "Keszthely",
    "Balatonalmádi",
    "Balatonboglár",
    "Balatonföldvár",
    "Balatonfüred",
    "Balatonkenese",
    "Balatonlelle",
    "Badacsonytomaj",
    "Fonyód",
    "Siófok",
    "Zamárdi",
    "Hévíz",
    "Tapolca",
    "Sümeg",
    "Zalakaros",
    "Marcali"
  ],
  "Italy": [
    "Roma",
    "Castel Fusano Milano",
    "Napoli",
    "Fuorigrotta Torino",
    "Nizza Millefonti Palermo",
    "Settecannoli Genova",
    "Ilario Bologna",
    "Savena Firenze",
    "Castello Bari",
    "San Pio Catania",
    "Primosole Venezia",
    "Malcontenta Verona",
    "Stelle Messina",
    "Gesso Padova",
    "Ponterotto Trieste",
    "Altura Taranto",
    "Tramontone Brescia",
    "Villaggio Violino Parma",
    "Vigatto Prato",
    "Macrolotto Modena",
    "Quattroville Reggio Calabria",
    "Reggio Emilia",
    "Roncocesi Perugia",
    "Cenerente Ravenna",
    "Ravenna Livorno",
    "Quercianella Rimini",
    "Villaggio Primo Maggio Cagliari",
    "Elia Foggia",
    "Arpinova Ferrara",
    "Monestirolo Salerno",
    "Rufoli Latina",
    "Tor Tre Ponti Monza",
    "Cazzaniga Sassari",
    "Prunizzedda Bergamo",
    "Sposi Pescara",
    "Pescara Colli Trento",
    "Spalliera Vicenza",
    "Capitello Bolzano",
    "Dodiciville Ancona",
    "Massignano Siracusa",
    "Targia Lucca",
    "Vicopelago Pisa",
    "La Vettola Siena",
    "Vico Alto Matera",
    "Borgo Venusio Lecce",
    "Villa Convento Como",
    "Garzola Amalfi",
    "Tovere Sorrento",
    "Sorrento Taormina",
    "Spisone Sanremo"
  ],
  "Netherlands": [
    "Amsterdam",
    "Rotterdam",
    "Den Haag",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
    "Apeldoorn",
    "Haarlem",
    "Arnhem",
    "Enschede",
    "Amersfoort",
    "Zaanstad",
    "’s-Hertogenbosch",
    "Zwolle",
    "Zoetermeer",
    "Leiden",
    "Maastricht",
    "Dordrecht",
    "Ede",
    "Leeuwarden",
    "Venlo",
    "Alkmaar",
    "Delft",
    "Deventer",
    "Sittard-Geleen",
    "Helmond",
    "Heerlen",
    "Hilversum",
    "Amstelveen",
    "Oss",
    "Roosendaal",
    "Schiedam",
    "Purmerend",
    "Lelystad",
    "Gouda",
    "Alphen aan den Rijn",
    "Hoorn",
    "Vlaardingen",
    "Assen",
    "Bergen op Zoom",
    "Middelburg",
    "Den Helder",
    "Zandvoort",
    "Volendam",
    "Giethoorn",
    "Valkenburg"
  ],
  "Portugal": [
    "Lisszabon",
    "Porto",
    "Vila Nova de Gaia",
    "Amadora",
    "Braga",
    "Coimbra",
    "Funchal",
    "Setúbal",
    "Almada",
    "Aveiro",
    "Guimarães",
    "Faro",
    "Évora",
    "Cascais",
    "Sintra",
    "Lagos",
    "Albufeira",
    "Portimão",
    "Óbidos",
    "Nazaré"
  ],
  "Spain": [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Zaragoza",
    "Sevilla",
    "Málaga",
    "Murcia",
    "Mallorca",
    "Gran Canaria",
    "Alicante",
    "Bilbao",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Llobregat",
    "Gasteiz",
    "Coruña",
    "Elche",
    "Granada",
    "Terrassa",
    "Badalona",
    "Oviedo",
    "Cartagena",
    "Sabadell",
    "Frontera",
    "Pamplona",
    "Tenerife",
    "Almería",
    "Henares",
    "San Sebastián",
    "Burgos",
    "Santander",
    "Plana",
    "Badajoz",
    "Salamanca",
    "Logroño",
    "Marbella",
    "León",
    "Tarragona",
    "Cádiz",
    "Girona",
    "Compostela",
    "Toledo",
    "Segovia",
    "Cuenca",
    "Cáceres",
    "Ronda",
    "Benidorm",
    "Ibiza"
  ],
  "Switzerland": [
    "Zürich",
    "Genf",
    "Bázel",
    "Lausanne",
    "Bern",
    "Winterthur",
    "Luzern",
    "St. Gallen",
    "Lugano",
    "Biel/Bienne",
    "Thun",
    "Köniz",
    "La Chaux-de-Fonds",
    "Fribourg",
    "Schaffhausen",
    "Chur",
    "Vernier",
    "Neuchâtel",
    "Uster",
    "Sion",
    "Lancy",
    "Emmen",
    "Yverdon-les-Bains",
    "Zug",
    "Kriens",
    "Rapperswil-Jona",
    "Montreux",
    "Frauenfeld",
    "Wetzikon",
    "Aarau",
    "Wil",
    "Bellinzona",
    "Baden",
    "Vevey",
    "Solothurn",
    "Interlaken",
    "Locarno",
    "Ascona",
    "Davos",
    "St. Moritz",
    "Zermatt",
    "Grindelwald",
    "Lauterbrunnen",
    "Engelberg",
    "Andermatt",
    "Gstaad",
    "Leukerbad",
    "Saas-Fee",
    "Appenzell",
    "Murten"
  ],
  "Taipei": [
    "Taipei",
    "New Taipei",
    "Taichung",
    "Kaohsiung",
    "Tainan",
    "Taoyuan",
    "Hsinchu",
    "Keelung",
    "Chiayi",
    "Hualien",
    "Taitung",
    "Yilan",
    "Nantou",
    "Pingtung",
    "Miaoli",
    "Changhua",
    "Yunlin / Douliu",
    "Magong / Penghu",
    "Jiufen",
    "Alishan"
  ],
  "UK": [
    "London",
    "Birmingham",
    "Manchester",
    "Liverpool",
    "Leeds",
    "Sheffield",
    "Bristol",
    "Leicester",
    "Nottingham",
    "Newcastle upon Tyne",
    "Bradford",
    "Coventry",
    "Southampton",
    "Portsmouth",
    "Plymouth",
    "Reading",
    "Stoke-on-Trent",
    "Derby",
    "Wolverhampton",
    "Brighton and Hove",
    "Hull",
    "Milton Keynes",
    "Northampton",
    "Luton",
    "Bournemouth",
    "Swindon",
    "Oxford",
    "York",
    "Cambridge",
    "Norwich",
    "Exeter",
    "Bath",
    "Canterbury",
    "Chester",
    "Durham",
    "Lancaster",
    "Salisbury",
    "Winchester",
    "Blackpool",
    "Scarborough",
    "Eastbourne",
    "Torquay",
    "Newquay",
    "Cheltenham",
    "Gloucester",
    "Ipswich",
    "Colchester",
    "Southend-on-Sea",
    "Middlesbrough",
    "Sunderland"
  ],
  "USA": [
    "NewYork City",
    "Los Angeles",
    "Houston",
    "Miami",
    "Chichago",
    "San Antonio",
    "San Diego",
    "Dallas",
    "Fort Worth",
    "JacksonVille",
    "Austin",
    "San Jose",
    "Charlotte",
    "Columbus",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Nashville",
    "Oklahoma City",
    "Washington",
    "El Paso",
    "Las Vegas",
    "Boston",
    "Portland",
    "Memphis",
    "Detroit",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Sacramento",
    "Kansas City",
    "Atlanta",
    "Colorado Spring",
    "Tucson",
    "Omaha",
    "Raleigh",
    "Virginia Beach",
    "Long Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "BakersField",
    "Wichita",
    "Arlington",
    "New Orleands",
    "Tampa",
    "Orlando",
    "Honolulu",
    "Fort Lauderdale",
    "Flagstaff",
    "Riverside",
    "Naples",
    "Salinas",
    "Buffalo",
    "Melburne",
    "Salt Lake City",
    "St Louis",
    "Savannah",
    "Charleston",
    "Key West",
    "Sedona",
    "Asheville",
    "Branson",
    "Gatlinburg",
    "Monterey",
    "Napa",
    "Sonoma",
    "Santa Fe"
  ]
};

export const COUNTRY_NAMES = Object.keys(COUNTRY_CITIES);
